# Generated by Django 3.1.7 on 2021-02-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': '1. Cargos',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('data_admissao', models.DateField(verbose_name='Data de admissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cargos', to='empresa.cargos', verbose_name='Cargo associado')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': '2. Pessoas',
            },
        ),
    ]
