# Generated by Django 3.1.7 on 2021-02-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoas',
            old_name='data_admissao',
            new_name='admissao',
        ),
    ]
