# Generated by Django 3.1.7 on 2021-02-26 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20210226_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=120)),
                ('bairro', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('admissao', models.DateField(verbose_name='Data de admissão')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cargos', to='empresa.cargos', verbose_name='Cargo associado')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': '2. Pessoas',
            },
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
