# Generated by Django 3.1.7 on 2021-02-26 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20210226_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargos',
            options={'verbose_name': 'cargo', 'verbose_name_plural': '2. Cargos'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name': 'endereço', 'verbose_name_plural': '1. Endereços'},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'verbose_name': 'funcionário', 'verbose_name_plural': '3. Funcionários'},
        ),
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.CharField(max_length=250, verbose_name='Solicitação')),
                ('data_solicitacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data da solicitação')),
                ('resolvido', models.BooleanField(verbose_name='Solicitação resolvida ?')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresa.funcionarios', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'solicitação',
                'verbose_name_plural': '4. Solicitações',
            },
        ),
    ]
