# Generated by Django 3.1.7 on 2021-02-27 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_auto_20210227_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alvos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('latitude_localizacao', models.FloatField(help_text='Latitude da localização do alvo registrado', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude da localização')),
                ('longitude_localizacao', models.FloatField(help_text='Longitude da localização do alvo registrado', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Longitude da localização')),
                ('data_expiracao', models.DateField(verbose_name='Data de expiração')),
            ],
            options={
                'verbose_name': 'alvo',
                'verbose_name_plural': '5. Alvos',
            },
        ),
    ]
