# Generated by Django 3.0.5 on 2021-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_alvos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='permissoes',
            field=models.ManyToManyField(blank=True, to='empresa.Permissoes', verbose_name='Permissões'),
        ),
    ]
